tabs:
#  - Tab 5
  - Tab 1
  - Tab 2
  - Tab 3
  - Tab 4

frames:
  - name: frame1
    tab:  Tab 4
    row:  1
    title: This is frame 1
  - name: frame2
    tab:  Tab 4
    row:  0
    title: This is frame 2
  - name: frame3
    tab:  Tab 4
    title: Where's frame 3
  - name: frameA
    tab:  Tab 1
    row:  1
    title: this is frameA in Tab 5

inputwidgets:
  - name:       input_0
    label:      Some bool
    tab:        Tab 1
    row:        0
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - frame:  frameA
        activewhen: ['', 0]
    outputdef:
      AMR-Wind: incflo.input_0
      
  - name: input_1
    label: input_1 description
    frame:  frameA
    inputtype: int 
    defaultval: 1
    visible: True

  - name: input_2
    label: "list input  "
    frame:  frameA
    inputtype: [int, float, str] 
    defaultval: [1, 2.0, stuff]

  - name: input_3
    label: "list of options"
    tab:  Tab 1
    inputtype: str
    optionlist: ['optionA', 'optionB']
    defaultval: 'optionA'

  - name: input_4
    label: "string input"
    tab:  Tab 1
    inputtype: str

  - name: label1
    label: "This is some label"
    labelonly: True
    tab:  Tab 1

  - name: input_5
    label: Calculated from input_1
    tab:   Tab 1
    inputtype: int 
    defaultval: 1
    visible: True

  - name:       bool1
    label:      bool 1
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - input:  listbox1
      - frame:  frameA

  - name:       bool2
    label:      bool 2
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1

  - name:       bool3
    label:      bool 3
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1

  - name:       mergedbool1
    label:       
    tab:        Tab 2
    inputtype:  mergedboollist
    mergedboollist:
      - ['bool1', 'on1', '']
      - ['bool2', 'on2', '']
      - ['bool3', 'on3', '']

  - name:       listbox1
    label:      Choose your option
    tab:        Tab 2
    inputtype:  listbox
    optionlist: ['frame1', 'frame2', 'optionC', 'filename1', 'optE', 'bool1'] 
    defaultval: optionC
    listboxopt: 
      selectmode: multiple
    ctrlelem:
      - frame: frame1
        activewhen: ['frame1', 1]
      - frame: frame2
        activewhen: ['frame2', 0]
      - input: filename1
        activewhen: ['filename1', 1]
      - input: input_2
        activewhen: ['filename1', 1]
    
  - name:       filename1
    label:      Choose a file
    tab:        Tab 2
    inputtype:  filename
    fileopenopt:
      selecttype: directory

  - name: label2
    label: "Some more helpful \"advice\""
    labelonly: True
    tab:  Tab 1


buttons:
  - name:  button1
    text:  mirror
    frame: frameA
    col:   1
    command: "partial(self.mirrorinputs, \"input_1\", \"input_5\")"

  - name: button
    text: Update Plot
    tab:  Tab 1
    command: self.updateplot

  - name: button
    text: Exit
    tab:  Tab 1
    row:  9
    command: self.quit

  - name: pullvars
    text: pull vars
    tab:  Tab 2
    command: "partial(pullvals, self.inputvars, statuslabel=self.statusbar)"
    
