tabs:
  - Tab 5
  - Tab 1
  - Tab 2
  - Tab 3
  - Tab 4

frames:
  - name: frame1
    tab:  Tab 4
    row:  1
    title: This is frame 1
  - name: frame2
    tab:  Tab 4
    row:  0
    title: This is frame 0
  - name: frame3
    tab:  Tab 4
    title: Where's frame 3
  - name: frameA
    tab:  Tab 5
    row:  1
    title: this is frameA in Tab 5

inputwidgets:
  - name: input_0
    label: Some bool
    tab:  Tab 5
    row: 0
    inputtype: bool
    defaultval: 1
    ctrlframe: frameA

  - name: input_1
    label: Some description here
    frame:  frameA
    inputtype: int 
    defaultval: 1

  - name: input_2
    label: "list input  "
    frame:  frameA
    inputtype: [int, float, str] 
    defaultval: [1, 2.0, stuff]

  - name: input_3
    label: "list of options"
    tab:  Tab 5
    inputtype: str
    optionlist: ['optionA', 'optionB']
    defaultval: 'optionA'

  - name: input_4
    label: "string input"
    tab:  Tab 5
    inputtype: str

  - name: label1
    label: "This is some label"
    labelonly: True
    tab:  Tab 5

  - name: label2
    label: "Some more helpful advice"
    labelonly: True
    tab:  Tab 5

