tabs:
#  - Tab 5
  - Tab 1
  - Tab 2
  - Tab 3
  - Tab 4

frames:
  - name: frame1
    tab:  Tab 4
    row:  1
    title: This is frame 1
  - name: frame2
    tab:  Tab 4
    row:  0
    title: This is frame 2
  - name: frame3
    tab:  Tab 4
    title: Where's frame 3
  - name: frameA
    tab:  Tab 1
    row:  1
    title: this is frameA in Tab 5

inputwidgets:
  - name:       input_0
    label:      Some bool
    tab:        Tab 1
    row:        0
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - frame:  frameA
        activewhen: ['', 0]
    outputdef:
      AMR-Wind: incflo.bool0
      
  - name: input_1
    label: input_1 description
    frame:  frameA
    inputtype: int 
    defaultval: 1
    visible: True
    outputdef:
      AMR-Wind: incflo.int1

  - name: input_2
    label: "list input  "
    frame:  frameA
    inputtype: [int, float, str] 
    defaultval: [1, 2.0, stuff]
    outputdef:
      AMR-Wind: incflo.list1

  - name: input_3
    label: "list of options"
    tab:  Tab 1
    inputtype: str
    optionlist: ['optionA', 'optionB']
    defaultval: 'optionA'

  - name: input_4
    label: "string input"
    tab:  Tab 1
    inputtype: str

  - name: label1
    label: "This is some label"
    labelonly: True
    tab:  Tab 1

  - name: input_5
    label: Calculated from input_1
    tab:   Tab 1
    inputtype: int 
    defaultval: 1
    visible: True

  - name:       bool1
    label:      bool 1
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - input:  listbox1
      - frame:  frameA

  - name:       bool2
    label:      bool 2
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1

  - name:       bool3
    label:      bool 3
    tab:        Tab 2
    inputtype:  bool
    defaultval: 1

  - name:       mergedbool1
    label:       
    tab:        Tab 2
    inputtype:  mergedboollist
    mergedboollist:
      - ['bool1', 'on1', 'off1']
      - ['bool2', 'on2', 'off2']
      - ['bool3', 'on3', 'off3']
    outputdef:
      AMR-Wind: incflo.mergedboollist1

  - name:       listbox1
    label:      Choose your option
    tab:        Tab 2
    inputtype:  listbox
    optionlist: ['frame1', 'frame2', 'optionC', 'filename1', 'optE', 'bool1'] 
    defaultval: optionC
    listboxopt: 
      selectmode: multiple
    ctrlelem:
      - frame: frame1
        activewhen: ['frame1', 1]
      - frame: frame2
        activewhen: ['frame2', 0]
      - input: filename1
        activewhen: ['filename1', 1]
      - input: input_2
        activewhen: ['filename1', 1]
    
  - name:       filename1
    label:      Choose a file
    tab:        Tab 2
    inputtype:  filename
    fileopenopt:
      selecttype: directory

  - name: label2
    label: "Some more helpful \"advice\""
    labelonly: True
    tab:  Tab 1


buttons:
  - name:  button1
    text:  mirror
    frame: frameA
    col:   1
    command: "partial(self.mirrorinputs, \"input_1\", \"input_5\")"

  - name: button
    text: Update Plot
    tab:  Tab 1
    command: self.updateplot

  - name: button
    text: Exit
    tab:  Tab 1
    row:  9
    command: self.quit

  - name: pullvars
    text: pull vars
    tab:  Tab 2
    command: "partial(pullvals, self.inputvars, statuslabel=self.statusbar)"

#  - name: openpopup
#    text: Open pop up vals    
#    tab:  Tab 2
#    command: "partial(self.launchpopupwin, 'popup2')" #self.popupwin
  
#  - name: printpopup
#    text: Print pop up vals    
#    tab:  Tab 2
#    command: self.printpuwindict

popupwindow:
  popup1:
    title:  Window title             # optional
    datakeyname:  popup1_name        # optional
    loadonstart:  False              # optional
    inputwidgets:
    - name:       popup1_name
      label:      Name of stuff
      inputtype:  str
      defaultval: name
    - name:       popup1_input0
      label:      Some bool
      inputtype:  bool
      defaultval: 1
      ctrlelem:
        - input:  popup1_input1
    - name:       popup1_input1
      label:      input_1 description
      inputtype:  int 
      defaultval: 123
    - name:       popup1_input2
      label:      input_2 description
      inputtype:  [float, float, float]
      defaultval: [-1, 0, 1]
  popup2:
    title:  Window title 2           # optional
    datakeyname:  popup2_name        # optional
    loadonstart:  True               # optional
    inputwidgets:
    - name:       popup2_name
      label:      Name of stuff
      inputtype:  str
      defaultval: name
    - name:       popup2_input0
      label:      Some bool
      inputtype:  bool
      defaultval: 1

listboxpopupwindows:
  - name:       listboxpopup1
    label:      List of stuff
    tab:        Tab 3
    row:        0                   # optional
    popupinput: popup1

setlistboxfromdict:
  listboxpopup1:
    item1:
      popup1_name:   name0
      popup1_input0: 0  
      popup1_input1: '10'
      popup1_input2: [0, 2, 1]
    item2:
      popup1_name:   name1
      popup1_input0: 1
      popup1_input1: 20      
      popup1_input2: ['1.1', '2.001', '1']
      
setfromdict:
  incflo.bool0: 1
  incflo.int1:  123
  incflo.list1: [-1, 3.1, stuffB]
  incflo.mergedboollist1: ['on1', 'off2', 'off3']
